# Generated by Django 5.0.7 on 2024-07-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietType', models.CharField(max_length=200)),
                ('dishName', models.CharField(max_length=200)),
                ('dishDifficulty', models.CharField(max_length=200)),
                ('dishBy', models.CharField(max_length=200)),
                ('dishType', models.CharField(max_length=200)),
                ('dishImage', models.CharField(max_length=200)),
                ('step1', models.CharField(max_length=200)),
                ('step2', models.CharField(max_length=200)),
                ('step3', models.CharField(max_length=200)),
                ('step4', models.CharField(max_length=200)),
                ('step5', models.CharField(max_length=200)),
                ('step6', models.CharField(max_length=200)),
                ('step7', models.CharField(max_length=200)),
                ('step8', models.CharField(max_length=200)),
                ('step9', models.CharField(max_length=200)),
                ('step10', models.CharField(max_length=200)),
                ('userAdded', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
